/// clientActions.js

export const SETCLIENTS = 'SETCLIENTS';
export const POSTCLIENT = 'POSTCLIENT';
export const PUTCLIENT = 'PUTCLIENT';
export const DELETECLIENT = 'DELETECLIENT';

//addressFormActions.js

export const SETSTREETADDRESS = 'SETSTREETADDRESS';
export const SETHOUSEADDRESS = 'SETHOUSEADDRESS';
export const SETFLATADDRESS = 'SETFLATADDRESS';
export const SETSTREETS = 'SETSTREETS';
export const SETCHOISEDSTREET = 'SETCHOISEDSTREET';
export const SETHOUSE = 'SETHOUSE';
export const SETCHOISEDHOUSE = 'SETCHOISEDHOUSE';
export const SETHOUSEFLATS = 'SETHOUSEFLATS';
export const SETCHOISEDHOUSEFLATS = 'SETCHOISEDHOUSEFLATS';